const user = [
  {
    name: "Gonzalo",
    lastname: "Tomasin",
    email: "gonzalotomasin@gmail.com",
    birthday: "July 20",
    password: "•••••••",
    telephone: 1123849560,
    address: "Antezana 247",
    Payment: "4444 4444 4444",
    Orders: {
      id: 1,
      date: "18 / 12 / 22",
      status: "xd",
      name: "Margherita",
      price: 10.99,
      image: "https://i.postimg.cc/J4qsjrzR/margherita.png",
      vegetarian: true,
      // userId: null,
      detail: {
        dough: "wholemeal flour",
        type: "gross",
        base: "milk cream",
        mozzarella: "vegan mozarella",
        toppingIngredients: ["Pineapple", "Mushrooms"],
        cheeseIngredients: [
          "Fontina Cheese",
          "Asiago Cheese",
          "Smoked Mozzarella Cheese",
        ],
        meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
      },
      category: "pizza",
    },
  },
  {
    name: "Gonzalo",
    lastname: "Tomasin",
    email: "gonzalotomasin@gmail.com",
    birthday: "July 20",
    password: "•••••••",
    telephone: 1123849560,
    address: "Antezana 247",
    Payment: "4444 4444 4444",
    Orders: {
      id: 2,
      date: "18 / 12 / 22",
      status: "xd",
      name: "Margherita",
      price: 10.99,
      image: "https://i.postimg.cc/J4qsjrzR/margherita.png",
      vegetarian: true,
      // userId: null,
      detail: {
        dough: "wholemeal flour",
        type: "gross",
        base: "milk cream",
        mozzarella: "vegan mozarella",
        toppingIngredients: ["Pineapple", "Mushrooms"],
        cheeseIngredients: [
          "Fontina Cheese",
          "Asiago Cheese",
          "Smoked Mozzarella Cheese",
        ],
        meatIngredients: ["Meatballs", "Pepperoni", "Bacon"],
      },
      category: "pizza",
    },
  },
];
export default user;
